CREATE USER C##BACKFRONT IDENTIFIED BY "backendfrontend"
DEFAULT TABLESPACE "SYSTEM"
TEMPORARY TABLESPACE "TEMP"

GRANT CONNECT TO C##BACKFRONT;
GRANT RESOURCE TO C##BACKFRONT;
GRANT ALL PRIVILEGES TO C##BACKFRONT;

DROP USER C##BACKFRONT